### PR TITLE
Compatibility Updates as of 2.0.204.48 - Moon Stair

### PR DESCRIPTION
**Pull request by jskrzypek**
Updates including those from Bee/Simon's fork https://github.com/simonfruehauf/QUDUX-2.0.203.56

### CODE REVIEW

**Comment by jskrzypek** [comment]
NB apparently this only fixes the errors with loading the mod, but doesn't actually restore full functionality... I'll try seeing if I can patch the warnings too, and see if that fixes the issue.

**Comment by egocarib** [comment]
Cool - I'll give this a try sometime this week!

**Comment by jskrzypek** [comment]
@egocarib thanks! this is still not working but now I finally found the information about the `Player.log` & `harmony.log.txt` files in the [Modding:Overview](https://wiki.cavesofqud.com/wiki/Modding:Overview) page of the wiki and found that there are errors w/ QudUX applying Harmony patches. This seems likely related:

From `Player.log`
```
MODERROR [QudUX] - Exception applying harmony patches: HarmonyLib.HarmonyException: Patching exception in method static System.String XRL.Annals.QudHistoryFactory::NameRuinsSite(HistoryKit.History history, System.Boolean& Proper, System.String& nameRoot) ---> System.ComponentModel.Win32Exception: Invalid data
  at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms (System.IntPtr start, System.UInt64 len, MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform+MmapProts prot) [0x00043] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable (System.IntPtr src, System.UInt32 size) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.DetourHelper.MakeWritable (MonoMod.RuntimeDetour.IDetourNativePlatform plat, MonoMod.RuntimeDetour.NativeDetourData detour) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest (System.Reflection.MethodInfo from, System.Reflection.MethodInfo to) [0x00035] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor () [0x0003f] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.Platforms.DetourRuntimeMonoPlatform..ctor () [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.DetourHelper.get_Runtime () [0x0003e] in <28a34da201e449be81fe5efb7481a26c>:0 
  at MonoMod.RuntimeDetour.DetourHelper.Pin[T] (T method) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]& finalInstructions) [0x00594] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00057] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x0015d] in <28a34da201e449be81fe5efb7481a26c>:0 
   --- End of inner exception stack trace ---
  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.PatchClassProcessor.Patch () [0x00084] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.Harmony.<PatchAll>b__10_0 (System.Type type) [0x00007] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) [0x00014] in <28a34da201e449be81fe5efb7481a26c>:0 
  at HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) [0x00006] in <28a34da201e449be81fe5efb7481a26c>:0 
  at XRL.ModInfo.ApplyHarmonyPatches () [0x00070] in <beb304b415964e3bb76d1e6a79f5bd5d>:0 
```

From `harmony.log.txt`:
```

### Exception from user "QudUX", Harmony v2.0.2.0
### Original: static System.String XRL.Annals.QudHistoryFactory::NameRuinsSite(HistoryKit.History history, System.Boolean& Proper, System.String& nameRoot)
### Patch class: QudUX.HarmonyPatches.Patch_XRL_Annals_QudHistoryFactory
### System.ComponentModel.Win32Exception (0x80004005): Invalid data
###   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms (System.IntPtr start, System.UInt64 len, MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform+MmapProts prot) [0x00043] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable (System.IntPtr src, System.UInt32 size) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.MakeWritable (MonoMod.RuntimeDetour.IDetourNativePlatform plat, MonoMod.RuntimeDetour.NativeDetourData detour) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest (System.Reflection.MethodInfo from, System.Reflection.MethodInfo to) [0x00035] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor () [0x0003f] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeMonoPlatform..ctor () [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime () [0x0003e] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.Pin[T] (T method) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]& finalInstructions) [0x00594] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00057] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x0015d] in <28a34da201e449be81fe5efb7481a26c>:0
### Exception from user "QudUX", Harmony v2.0.2.0
### Original: static System.String XRL.Annals.QudHistoryFactory::NameRuinsSite(HistoryKit.History history, System.Boolean& Proper, System.String& nameRoot)
### Patch class: QudUX.HarmonyPatches.Patch_XRL_Annals_QudHistoryFactory
### System.ComponentModel.Win32Exception (0x80004005): Invalid data
###   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms (System.IntPtr start, System.UInt64 len, MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform+MmapProts prot) [0x00043] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable (System.IntPtr src, System.UInt32 size) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.MakeWritable (MonoMod.RuntimeDetour.IDetourNativePlatform plat, MonoMod.RuntimeDetour.NativeDetourData detour) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest (System.Reflection.MethodInfo from, System.Reflection.MethodInfo to) [0x00035] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor () [0x0003f] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeMonoPlatform..ctor () [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime () [0x0003e] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at MonoMod.RuntimeDetour.DetourHelper.Pin[T] (T method) [0x00000] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.MethodPatcher.CreateReplacement (System.Collections.Generic.Dictionary`2[System.Int32,HarmonyLib.CodeInstruction]& finalInstructions) [0x00594] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) [0x00057] in <28a34da201e449be81fe5efb7481a26c>:0 
###   at HarmonyLib.PatchClassProcessor.ProcessPatchJob (HarmonyLib.PatchJobs`1+Job[T] job) [0x0015d] in <28a34da201e449be81fe5efb7481a26c>:0
```

**Comment by egocarib** [comment]
I am going to close this PR request for a few reasons:
- It never seemed like it got the Harmony patches working again properly
- It is very hard to review in its current state because it changed the indentation of every file. So there is no easy way to review the line-level changes
- There is a new PR open that appears to be more comprehensive and up-to-date.

Thank you for your work on this in any case - I do appreciate your efforts and will be glad to look at future changes you might submit. Sorry that this one wasn't able to get merged in!

**Pull request closed without merging**
